config/routes.rb
Rails.application.routes.draw do

  resources :reqs
  resources :books

  post 'binary',      to: 'binary#post'
  post 'binary/info', to: 'binary#info'

  get 'hello/index', to: "healthcheck#hello"
  get 'hello/echo' , to: "healthcheck#echo"

  get 'version'    , to: 'healthcheck#show_version'
  get 'env'        , to: 'healthcheck#show_env'
  get 'sleep'      , to: 'healthcheck#get_sleep'

  post 'mqtt/auth',  to: 'mqtt#auth'
  post 'mqtt/auth2', to: 'mqtt#auth2'
  post 'mqtt/auth3', to: 'mqtt#auth3'

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/binary_controller.rb
require 'base64'

class BinaryController < ApplicationController

  def post
    body = request.body.read
    send_data body, type: "application/octet-stream", dispatch: :inline
  end

  def info
    body = request.body.read
    size = body.bytesize
    type = request.content_type
    render json: { size: size, type: type, body: Base64.encode64(body) }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title)
    end
end

app/controllers/healthcheck_controller.rb
class HealthcheckController < ApplicationController
  def hello
    logger.info('HealthcheckController#hello')
    render json: {hello: 'world' }
  end

  def echo
    render json: {echo: params[:st]}
  end

  VERSION = File.read(Rails.root.join("VERSION").to_s).strip
  def show_version
    render json: {version: VERSION}
  end

  def show_env
    # sort by key
    render json: ENV.keys.sort.each_with_object({}){|k,d| d[k] = ENV[k]}
  end

  def get_sleep
    t = (params[:t] || 1).to_i.seconds
    sleep(t)
    render json: {sleep: t}
  end
end

app/controllers/mqtt_controller.rb
# coding: utf-8
class MqttController < ApplicationController

  # POST: /mqtt/auth
  # MQTTの認証を行なう。
  def auth
    response.headers['X-MQTT-AUTH'] = "YES"
    auth = {
      publish_topics:   %w(hello/index worker/pub books/create books/update books/delete_all),
      subscribe_topics: %w(rooms/001 test/test)
    }
    render json: auth.to_json
  end

  # POST: /mqtt/auth2
  # MQTTの認証を行なう。
  # 認証時のボディが空
  def auth2
    response.headers['X-MQTT-AUTH'] = "YES"
    auth = {}
    render json: auth.to_json
  end

  # POST: /mqtt/auth3
  # MQTTの認証を行なう。
  # 認証時のpub/subトピックが空
  def auth3
    response.headers['X-MQTT-AUTH'] = "YES"
    auth = {
      publish_topics:   [],
      subscribe_topics: []
    }
    render json: auth.to_json
  end

end

app/controllers/reqs_controller.rb
require 'base64'

class ReqsController < ApplicationController

  respond_to :json

  # GET: /reqs
  def index
    show_data()
  end

  # GET: /reqs:id
  def show
    show_data()
  end

  # POST: /reqs
  def create
    show_data()
  end

  # PUT: /reqs/:id
  def update
    show_data()
  end

  # DELETE: /reqs/:id
  def destroy
    show_data()
  end


  private

  def show_data
    r = request
    body = r.body.read
    begin
      {body: body}.to_json
    rescue Encoding::UndefinedConversionError
      body = Base64.strict_encode64(body)
    rescue JSON::GeneratorError
      body = Base64.strict_encode64(body)
    end
    dat = {
      method: r.request_method,
      path: r.path_info,
      query: r.query_string,
      headers: r.headers.each_with_object([]){|(k,v), arr| arr << [k, v] if k =~ /^HTTP_/ },
      body: body,
      params: params
    }
    render :json => dat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/healthcheck_helper.rb
module HealthcheckHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MagellanRailsExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>